version: 2.1
orbs:
  saucectl: saucelabs/saucectl-run@1.0.0

jobs:
  test-xcuitest:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - saucectl/saucectl-run

workflows:
  version: 2
  default_workflow:
    jobs:
      - test-xcuitest